package bettershulkerhud.gui;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;

import java.util.Set;

public enum BundleCategory {
    ALL("全部", Items.COMPASS),
    BLOCKS("方块", Items.GRASS_BLOCK),
    NON_FULL_BLOCKS("不完整方块", Items.SPRUCE_DOOR),
    PLANTS("植物", Items.CHERRY_SAPLING),
    FOOD("食物", Items.BREAD),
    TOOLS_AND_EQUIPMENT("工具和装备", Items.DIAMOND_CHESTPLATE),
    MISC("杂物", Items.LEATHER),
    MINERALS("矿物", Items.DIAMOND);

    private final String displayName;
    private final Item iconItem;
    private Set<String> itemIds;

    BundleCategory(String displayName, Item iconItem) {
        this.displayName = displayName;
        this.iconItem = iconItem;
        this.itemIds = Set.of();
    }

    public String getDisplayName() { return displayName; }
    public ItemStack getIcon() { return new ItemStack(iconItem); }
    public void setItemIds(Set<String> ids) { this.itemIds = Set.copyOf(ids); }
    public boolean matches(String registryKey) {
        if (this == ALL) return true;
        return itemIds.contains(registryKey);
    }

    public static void registerCategoryItems() {
        BLOCKS.setItemIds(Set.of(
            "minecraft:acacia_log", "minecraft:acacia_planks", "minecraft:acacia_wood",
            "minecraft:amethyst_block", "minecraft:ancient_debris", "minecraft:andesite",
            "minecraft:bamboo_block", "minecraft:bamboo_mosaic", "minecraft:bamboo_planks",
            "minecraft:basalt", "minecraft:bedrock", "minecraft:birch_log",
            "minecraft:birch_planks", "minecraft:birch_wood", "minecraft:black_concrete",
            "minecraft:black_concrete_powder", "minecraft:black_glazed_terracotta",
            "minecraft:black_stained_glass", "minecraft:black_terracotta", "minecraft:black_wool",
            "minecraft:blackstone", "minecraft:blue_concrete", "minecraft:blue_concrete_powder",
            "minecraft:blue_glazed_terracotta", "minecraft:blue_ice", "minecraft:blue_stained_glass",
            "minecraft:blue_terracotta", "minecraft:blue_wool", "minecraft:bone_block",
            "minecraft:brain_coral_block", "minecraft:bricks", "minecraft:brown_concrete",
            "minecraft:brown_concrete_powder", "minecraft:brown_glazed_terracotta",
            "minecraft:brown_mushroom_block", "minecraft:brown_stained_glass",
            "minecraft:brown_terracotta", "minecraft:brown_wool", "minecraft:bubble_coral_block",
            "minecraft:budding_amethyst", "minecraft:calcite", "minecraft:cherry_log",
            "minecraft:cherry_planks", "minecraft:cherry_wood", "minecraft:chiseled_copper",
            "minecraft:chiseled_deepslate", "minecraft:chiseled_nether_bricks",
            "minecraft:chiseled_polished_blackstone", "minecraft:chiseled_quartz_block",
            "minecraft:chiseled_red_sandstone", "minecraft:chiseled_resin_bricks",
            "minecraft:chiseled_sandstone", "minecraft:chiseled_stone_bricks",
            "minecraft:chiseled_tuff", "minecraft:chiseled_tuff_bricks", "minecraft:clay",
            "minecraft:coal_block", "minecraft:coal_ore", "minecraft:coarse_dirt",
            "minecraft:cobbled_deepslate", "minecraft:cobblestone", "minecraft:copper_block",
            "minecraft:copper_ore", "minecraft:cracked_deepslate_bricks",
            "minecraft:cracked_deepslate_tiles", "minecraft:cracked_nether_bricks",
            "minecraft:cracked_polished_blackstone_bricks", "minecraft:cracked_stone_bricks",
            "minecraft:crimson_hyphae", "minecraft:crimson_nylium", "minecraft:crimson_planks",
            "minecraft:crimson_stem", "minecraft:crying_obsidian", "minecraft:cut_copper",
            "minecraft:cut_red_sandstone", "minecraft:cut_sandstone", "minecraft:cyan_concrete",
            "minecraft:cyan_concrete_powder", "minecraft:cyan_glazed_terracotta",
            "minecraft:cyan_stained_glass", "minecraft:cyan_terracotta", "minecraft:cyan_wool",
            "minecraft:dark_oak_log", "minecraft:dark_oak_planks", "minecraft:dark_oak_wood",
            "minecraft:dark_prismarine", "minecraft:dead_brain_coral_block",
            "minecraft:dead_bubble_coral_block", "minecraft:dead_fire_coral_block",
            "minecraft:dead_horn_coral_block", "minecraft:dead_tube_coral_block",
            "minecraft:deepslate", "minecraft:deepslate_bricks", "minecraft:deepslate_coal_ore",
            "minecraft:deepslate_copper_ore", "minecraft:deepslate_diamond_ore",
            "minecraft:deepslate_emerald_ore", "minecraft:deepslate_gold_ore",
            "minecraft:deepslate_iron_ore", "minecraft:deepslate_lapis_ore",
            "minecraft:deepslate_redstone_ore", "minecraft:deepslate_tiles",
            "minecraft:diamond_block", "minecraft:diamond_ore", "minecraft:diorite",
            "minecraft:dirt", "minecraft:dirt_path", "minecraft:dried_kelp_block",
            "minecraft:emerald_block", "minecraft:emerald_ore", "minecraft:end_stone",
            "minecraft:end_stone_bricks", "minecraft:exposed_chiseled_copper",
            "minecraft:exposed_copper", "minecraft:exposed_cut_copper",
            "minecraft:fire_coral_block", "minecraft:glass", "minecraft:glowstone",
            "minecraft:gold_block", "minecraft:gold_ore", "minecraft:granite",
            "minecraft:grass_block", "minecraft:gravel", "minecraft:gray_concrete",
            "minecraft:gray_concrete_powder", "minecraft:gray_glazed_terracotta",
            "minecraft:gray_stained_glass", "minecraft:gray_terracotta", "minecraft:gray_wool",
            "minecraft:green_concrete", "minecraft:green_concrete_powder",
            "minecraft:green_glazed_terracotta", "minecraft:green_stained_glass",
            "minecraft:green_terracotta", "minecraft:green_wool", "minecraft:honey_block",
            "minecraft:honeycomb_block", "minecraft:horn_coral_block", "minecraft:ice",
            "minecraft:infested_chiseled_stone_bricks", "minecraft:infested_cobblestone",
            "minecraft:infested_cracked_stone_bricks", "minecraft:infested_deepslate",
            "minecraft:infested_mossy_stone_bricks", "minecraft:infested_stone",
            "minecraft:infested_stone_bricks", "minecraft:iron_block", "minecraft:iron_ore",
            "minecraft:jungle_log", "minecraft:jungle_planks", "minecraft:jungle_wood",
            "minecraft:lapis_block", "minecraft:lapis_ore", "minecraft:light_blue_concrete",
            "minecraft:light_blue_concrete_powder", "minecraft:light_blue_glazed_terracotta",
            "minecraft:light_blue_stained_glass", "minecraft:light_blue_terracotta",
            "minecraft:light_blue_wool", "minecraft:light_gray_concrete",
            "minecraft:light_gray_concrete_powder", "minecraft:light_gray_glazed_terracotta",
            "minecraft:light_gray_stained_glass", "minecraft:light_gray_terracotta",
            "minecraft:light_gray_wool", "minecraft:lime_concrete", "minecraft:lime_concrete_powder",
            "minecraft:lime_glazed_terracotta", "minecraft:lime_stained_glass",
            "minecraft:lime_terracotta", "minecraft:lime_wool", "minecraft:magenta_concrete",
            "minecraft:magenta_concrete_powder", "minecraft:magenta_glazed_terracotta",
            "minecraft:magenta_stained_glass", "minecraft:magenta_terracotta",
            "minecraft:magenta_wool", "minecraft:mangrove_log", "minecraft:mangrove_planks",
            "minecraft:mangrove_wood", "minecraft:moss_block", "minecraft:mossy_cobblestone",
            "minecraft:mossy_stone_bricks", "minecraft:mud", "minecraft:mud_bricks",
            "minecraft:mycelium", "minecraft:nether_bricks", "minecraft:nether_gold_ore",
            "minecraft:nether_quartz_ore", "minecraft:nether_wart_block", "minecraft:netherite_block",
            "minecraft:netherrack", "minecraft:oak_log", "minecraft:oak_planks",
            "minecraft:oak_wood", "minecraft:obsidian", "minecraft:ochre_froglight",
            "minecraft:orange_concrete", "minecraft:orange_concrete_powder",
            "minecraft:orange_glazed_terracotta", "minecraft:orange_stained_glass",
            "minecraft:orange_terracotta", "minecraft:orange_wool", "minecraft:oxidized_chiseled_copper",
            "minecraft:oxidized_copper", "minecraft:oxidized_cut_copper", "minecraft:packed_ice",
            "minecraft:packed_mud", "minecraft:pale_moss_block", "minecraft:pale_oak_log",
            "minecraft:pale_oak_planks", "minecraft:pale_oak_wood", "minecraft:pearlescent_froglight",
            "minecraft:pink_concrete", "minecraft:pink_concrete_powder",
            "minecraft:pink_glazed_terracotta", "minecraft:pink_stained_glass",
            "minecraft:pink_terracotta", "minecraft:pink_wool", "minecraft:podzol",
            "minecraft:polished_andesite", "minecraft:polished_basalt",
            "minecraft:polished_blackstone", "minecraft:polished_blackstone_bricks",
            "minecraft:polished_deepslate", "minecraft:polished_diorite",
            "minecraft:polished_granite", "minecraft:polished_tuff", "minecraft:prismarine",
            "minecraft:prismarine_bricks", "minecraft:purple_concrete",
            "minecraft:purple_concrete_powder", "minecraft:purple_glazed_terracotta",
            "minecraft:purple_stained_glass", "minecraft:purple_terracotta",
            "minecraft:purple_wool", "minecraft:purpur_block", "minecraft:purpur_pillar",
            "minecraft:quartz_block", "minecraft:quartz_bricks", "minecraft:quartz_pillar",
            "minecraft:raw_copper_block", "minecraft:raw_gold_block", "minecraft:raw_iron_block",
            "minecraft:red_concrete", "minecraft:red_concrete_powder",
            "minecraft:red_glazed_terracotta", "minecraft:red_mushroom_block",
            "minecraft:red_nether_bricks", "minecraft:red_sand", "minecraft:red_sandstone",
            "minecraft:red_stained_glass", "minecraft:red_terracotta", "minecraft:red_wool",
            "minecraft:redstone_block", "minecraft:redstone_ore", "minecraft:reinforced_deepslate",
            "minecraft:resin_block", "minecraft:resin_bricks", "minecraft:rooted_dirt",
            "minecraft:sand", "minecraft:sandstone", "minecraft:sculk", "minecraft:sea_lantern",
            "minecraft:shroomlight", "minecraft:slime_block", "minecraft:smooth_basalt",
            "minecraft:smooth_quartz", "minecraft:smooth_red_sandstone",
            "minecraft:smooth_sandstone", "minecraft:smooth_stone", "minecraft:snow_block",
            "minecraft:soul_sand", "minecraft:soul_soil", "minecraft:sponge",
            "minecraft:spruce_log", "minecraft:spruce_planks", "minecraft:spruce_wood",
            "minecraft:stone", "minecraft:stone_bricks", "minecraft:stripped_acacia_log",
            "minecraft:stripped_acacia_wood", "minecraft:stripped_bamboo_block",
            "minecraft:stripped_birch_log", "minecraft:stripped_birch_wood",
            "minecraft:stripped_cherry_log", "minecraft:stripped_cherry_wood",
            "minecraft:stripped_crimson_hyphae", "minecraft:stripped_crimson_stem",
            "minecraft:stripped_dark_oak_log", "minecraft:stripped_dark_oak_wood",
            "minecraft:stripped_jungle_log", "minecraft:stripped_jungle_wood",
            "minecraft:stripped_mangrove_log", "minecraft:stripped_mangrove_wood",
            "minecraft:stripped_oak_log", "minecraft:stripped_oak_wood",
            "minecraft:stripped_pale_oak_log", "minecraft:stripped_pale_oak_wood",
            "minecraft:stripped_spruce_log", "minecraft:stripped_spruce_wood",
            "minecraft:stripped_warped_hyphae", "minecraft:stripped_warped_stem",
            "minecraft:suspicious_gravel", "minecraft:suspicious_sand", "minecraft:terracotta",
            "minecraft:tinted_glass", "minecraft:tube_coral_block", "minecraft:tuff",
            "minecraft:tuff_bricks", "minecraft:verdant_froglight", "minecraft:warped_hyphae",
            "minecraft:warped_nylium", "minecraft:warped_planks", "minecraft:warped_stem",
            "minecraft:warped_wart_block", "minecraft:waxed_chiseled_copper",
            "minecraft:waxed_copper_block", "minecraft:waxed_cut_copper",
            "minecraft:waxed_exposed_chiseled_copper", "minecraft:waxed_exposed_copper",
            "minecraft:waxed_exposed_cut_copper", "minecraft:waxed_oxidized_chiseled_copper",
            "minecraft:waxed_oxidized_copper", "minecraft:waxed_oxidized_cut_copper",
            "minecraft:waxed_weathered_chiseled_copper", "minecraft:waxed_weathered_copper",
            "minecraft:waxed_weathered_cut_copper", "minecraft:weathered_chiseled_copper",
            "minecraft:weathered_copper", "minecraft:weathered_cut_copper",
            "minecraft:wet_sponge", "minecraft:white_concrete", "minecraft:white_concrete_powder",
            "minecraft:white_glazed_terracotta", "minecraft:white_stained_glass",
            "minecraft:white_terracotta", "minecraft:white_wool", "minecraft:yellow_concrete",
            "minecraft:yellow_concrete_powder", "minecraft:yellow_glazed_terracotta",
            "minecraft:yellow_stained_glass", "minecraft:yellow_terracotta", "minecraft:yellow_wool"
        ));
        NON_FULL_BLOCKS.setItemIds(Set.of(
            "minecraft:acacia_button", "minecraft:acacia_door", "minecraft:acacia_fence",
            "minecraft:acacia_fence_gate", "minecraft:acacia_hanging_sign", "minecraft:acacia_pressure_plate",
            "minecraft:acacia_sign", "minecraft:acacia_slab", "minecraft:acacia_stairs", "minecraft:acacia_trapdoor",
            "minecraft:activator_rail", "minecraft:amethyst_cluster", "minecraft:andesite_slab",
            "minecraft:andesite_stairs", "minecraft:andesite_wall", "minecraft:anvil", "minecraft:armor_stand",
            "minecraft:bamboo_button", "minecraft:bamboo_door", "minecraft:bamboo_fence", "minecraft:bamboo_fence_gate",
            "minecraft:bamboo_hanging_sign", "minecraft:bamboo_mosaic_slab", "minecraft:bamboo_mosaic_stairs",
            "minecraft:bamboo_pressure_plate", "minecraft:bamboo_shelf", "minecraft:bamboo_sign",
            "minecraft:bamboo_slab", "minecraft:bamboo_stairs", "minecraft:bamboo_trapdoor", "minecraft:barrel",
            "minecraft:beacon", "minecraft:bee_nest", "minecraft:beehive", "minecraft:bell",
            "minecraft:birch_button", "minecraft:birch_door", "minecraft:birch_fence", "minecraft:birch_fence_gate",
            "minecraft:birch_hanging_sign", "minecraft:birch_pressure_plate", "minecraft:birch_shelf",
            "minecraft:birch_sign", "minecraft:birch_slab", "minecraft:birch_stairs", "minecraft:birch_trapdoor",
            "minecraft:black_banner", "minecraft:black_bed", "minecraft:black_candle", "minecraft:black_carpet",
            "minecraft:black_stained_glass_pane", "minecraft:blackstone_slab", "minecraft:blackstone_stairs",
            "minecraft:blackstone_wall", "minecraft:blast_furnace", "minecraft:blue_banner", "minecraft:blue_bed",
            "minecraft:blue_candle", "minecraft:blue_carpet", "minecraft:blue_stained_glass_pane",
            "minecraft:bookshelf", "minecraft:brain_coral", "minecraft:brain_coral_fan", "minecraft:brewing_stand",
            "minecraft:brick_slab", "minecraft:brick_stairs", "minecraft:brick_wall", "minecraft:brown_banner",
            "minecraft:brown_bed", "minecraft:brown_candle", "minecraft:brown_carpet",
            "minecraft:brown_stained_glass_pane", "minecraft:bubble_coral", "minecraft:bubble_coral_fan",
            "minecraft:calibrated_sculk_sensor", "minecraft:campfire", "minecraft:candle", "minecraft:cartography_table",
            "minecraft:cauldron", "minecraft:cherry_button", "minecraft:cherry_door", "minecraft:cherry_fence",
            "minecraft:cherry_fence_gate", "minecraft:cherry_hanging_sign", "minecraft:cherry_pressure_plate",
            "minecraft:cherry_shelf", "minecraft:cherry_sign", "minecraft:cherry_slab", "minecraft:cherry_stairs",
            "minecraft:cherry_trapdoor", "minecraft:chipped_anvil", "minecraft:chiseled_bookshelf",
            "minecraft:cobbled_deepslate_slab", "minecraft:cobbled_deepslate_stairs", "minecraft:cobbled_deepslate_wall",
            "minecraft:cobblestone_slab", "minecraft:cobblestone_stairs", "minecraft:cobblestone_wall", "minecraft:cobweb",
            "minecraft:comparator", "minecraft:composter", "minecraft:conduit", "minecraft:copper_bars",
            "minecraft:copper_bulb", "minecraft:copper_chain", "minecraft:copper_door", "minecraft:copper_golem_statue",
            "minecraft:copper_grate", "minecraft:copper_lantern", "minecraft:copper_torch", "minecraft:copper_trapdoor",
            "minecraft:crafter", "minecraft:crafting_table", "minecraft:creaking_heart", "minecraft:creeper_head",
            "minecraft:crimson_button", "minecraft:crimson_door", "minecraft:crimson_fence", "minecraft:crimson_fence_gate",
            "minecraft:crimson_hanging_sign", "minecraft:crimson_pressure_plate", "minecraft:crimson_shelf",
            "minecraft:crimson_sign", "minecraft:crimson_slab", "minecraft:crimson_stairs", "minecraft:crimson_trapdoor",
            "minecraft:cut_copper_slab", "minecraft:cut_copper_stairs", "minecraft:cut_red_sandstone_slab",
            "minecraft:cut_sandstone_slab", "minecraft:cyan_banner", "minecraft:cyan_bed", "minecraft:cyan_candle",
            "minecraft:cyan_carpet", "minecraft:cyan_stained_glass_pane", "minecraft:damaged_anvil",
            "minecraft:dark_oak_button", "minecraft:dark_oak_door", "minecraft:dark_oak_fence",
            "minecraft:dark_oak_fence_gate", "minecraft:dark_oak_hanging_sign", "minecraft:dark_oak_pressure_plate",
            "minecraft:dark_oak_shelf", "minecraft:dark_oak_sign", "minecraft:dark_oak_slab", "minecraft:dark_oak_stairs",
            "minecraft:dark_oak_trapdoor", "minecraft:dark_prismarine_slab", "minecraft:dark_prismarine_stairs",
            "minecraft:daylight_detector", "minecraft:dead_brain_coral", "minecraft:dead_brain_coral_fan",
            "minecraft:dead_bubble_coral", "minecraft:dead_bubble_coral_fan", "minecraft:dead_fire_coral",
            "minecraft:dead_fire_coral_fan", "minecraft:dead_horn_coral", "minecraft:dead_horn_coral_fan",
            "minecraft:dead_tube_coral", "minecraft:dead_tube_coral_fan", "minecraft:decorated_pot",
            "minecraft:deepslate_brick_slab", "minecraft:deepslate_brick_stairs", "minecraft:deepslate_brick_wall",
            "minecraft:deepslate_tile_slab", "minecraft:deepslate_tile_stairs", "minecraft:deepslate_tile_wall",
            "minecraft:detector_rail", "minecraft:diorite_slab", "minecraft:diorite_stairs", "minecraft:diorite_wall",
            "minecraft:dispenser", "minecraft:dragon_egg", "minecraft:dragon_head", "minecraft:dried_ghast",
            "minecraft:dropper", "minecraft:enchanting_table", "minecraft:end_crystal", "minecraft:end_portal_frame",
            "minecraft:end_rod", "minecraft:end_stone_brick_slab", "minecraft:end_stone_brick_stairs",
            "minecraft:end_stone_brick_wall", "minecraft:exposed_copper_bars", "minecraft:exposed_copper_bulb",
            "minecraft:exposed_copper_chain", "minecraft:exposed_copper_door", "minecraft:exposed_copper_golem_statue",
            "minecraft:exposed_copper_grate", "minecraft:exposed_copper_lantern", "minecraft:exposed_copper_trapdoor",
            "minecraft:exposed_cut_copper_slab", "minecraft:exposed_cut_copper_stairs", "minecraft:exposed_lightning_rod",
            "minecraft:fire_coral", "minecraft:fire_coral_fan", "minecraft:fletching_table", "minecraft:flower_pot",
            "minecraft:furnace", "minecraft:glass_pane", "minecraft:glow_item_frame", "minecraft:granite_slab",
            "minecraft:granite_stairs", "minecraft:granite_wall", "minecraft:gray_banner", "minecraft:gray_bed",
            "minecraft:gray_candle", "minecraft:gray_carpet", "minecraft:gray_stained_glass_pane",
            "minecraft:green_banner", "minecraft:green_bed", "minecraft:green_candle", "minecraft:green_carpet",
            "minecraft:green_stained_glass_pane", "minecraft:grindstone", "minecraft:heavy_weighted_pressure_plate",
            "minecraft:honey_block", "minecraft:hopper", "minecraft:horn_coral", "minecraft:horn_coral_fan",
            "minecraft:iron_bars", "minecraft:iron_chain", "minecraft:iron_door", "minecraft:iron_trapdoor",
            "minecraft:item_frame", "minecraft:jukebox", "minecraft:jungle_button", "minecraft:jungle_door",
            "minecraft:jungle_fence", "minecraft:jungle_fence_gate", "minecraft:jungle_hanging_sign",
            "minecraft:jungle_pressure_plate", "minecraft:jungle_shelf", "minecraft:jungle_sign",
            "minecraft:jungle_slab", "minecraft:jungle_stairs", "minecraft:jungle_trapdoor", "minecraft:ladder",
            "minecraft:lantern", "minecraft:large_amethyst_bud", "minecraft:lectern", "minecraft:lever",
            "minecraft:light_blue_banner", "minecraft:light_blue_bed", "minecraft:light_blue_candle",
            "minecraft:light_blue_carpet", "minecraft:light_blue_stained_glass_pane", "minecraft:light_gray_banner",
            "minecraft:light_gray_bed", "minecraft:light_gray_candle", "minecraft:light_gray_carpet",
            "minecraft:light_gray_stained_glass_pane", "minecraft:light_weighted_pressure_plate",
            "minecraft:lightning_rod", "minecraft:lime_banner", "minecraft:lime_bed", "minecraft:lime_candle",
            "minecraft:lime_carpet", "minecraft:lime_stained_glass_pane", "minecraft:lodestone", "minecraft:loom",
            "minecraft:magenta_banner", "minecraft:magenta_bed", "minecraft:magenta_candle",
            "minecraft:magenta_carpet", "minecraft:magenta_stained_glass_pane", "minecraft:mangrove_button",
            "minecraft:mangrove_door", "minecraft:mangrove_fence", "minecraft:mangrove_fence_gate",
            "minecraft:mangrove_hanging_sign", "minecraft:mangrove_pressure_plate", "minecraft:mangrove_sign",
            "minecraft:mangrove_slab", "minecraft:mangrove_stairs", "minecraft:mangrove_trapdoor",
            "minecraft:medium_amethyst_bud", "minecraft:mossy_cobblestone_slab", "minecraft:mossy_cobblestone_stairs",
            "minecraft:mossy_cobblestone_wall", "minecraft:mossy_stone_brick_slab", "minecraft:mossy_stone_brick_stairs",
            "minecraft:mossy_stone_brick_wall", "minecraft:mud_brick_slab", "minecraft:mud_brick_stairs",
            "minecraft:mud_brick_wall", "minecraft:nether_brick_fence", "minecraft:nether_brick_slab",
            "minecraft:nether_brick_stairs", "minecraft:nether_brick_wall", "minecraft:note_block",
            "minecraft:oak_button", "minecraft:oak_door", "minecraft:oak_fence", "minecraft:oak_fence_gate",
            "minecraft:oak_hanging_sign", "minecraft:oak_pressure_plate", "minecraft:oak_shelf",
            "minecraft:oak_sign", "minecraft:oak_slab", "minecraft:oak_stairs", "minecraft:oak_trapdoor",
            "minecraft:observer", "minecraft:orange_banner", "minecraft:orange_bed", "minecraft:orange_candle",
            "minecraft:orange_carpet", "minecraft:orange_stained_glass_pane", "minecraft:oxidized_copper_bars",
            "minecraft:oxidized_copper_bulb", "minecraft:oxidized_copper_chain", "minecraft:oxidized_copper_door",
            "minecraft:oxidized_copper_golem_statue", "minecraft:oxidized_copper_grate",
            "minecraft:oxidized_copper_lantern", "minecraft:oxidized_copper_trapdoor",
            "minecraft:oxidized_cut_copper_slab", "minecraft:oxidized_cut_copper_stairs",
            "minecraft:oxidized_lightning_rod", "minecraft:painting", "minecraft:pale_oak_button",
            "minecraft:pale_oak_door", "minecraft:pale_oak_fence", "minecraft:pale_oak_fence_gate",
            "minecraft:pale_oak_hanging_sign", "minecraft:pale_oak_pressure_plate", "minecraft:pale_oak_shelf",
            "minecraft:pale_oak_sign", "minecraft:pale_oak_slab", "minecraft:pale_oak_stairs",
            "minecraft:pale_oak_trapdoor", "minecraft:piglin_head", "minecraft:pink_banner", "minecraft:pink_bed",
            "minecraft:pink_candle", "minecraft:pink_carpet", "minecraft:pink_stained_glass_pane", "minecraft:piston",
            "minecraft:player_head", "minecraft:pointed_dripstone", "minecraft:polished_andesite_slab",
            "minecraft:polished_andesite_stairs", "minecraft:polished_blackstone_brick_slab",
            "minecraft:polished_blackstone_brick_stairs", "minecraft:polished_blackstone_brick_wall",
            "minecraft:polished_blackstone_button", "minecraft:polished_blackstone_pressure_plate",
            "minecraft:polished_blackstone_stairs", "minecraft:polished_blackstone_wall",
            "minecraft:polished_deepslate_slab", "minecraft:polished_deepslate_stairs",
            "minecraft:polished_deepslate_wall", "minecraft:polished_diorite_slab",
            "minecraft:polished_diorite_stairs", "minecraft:polished_granite_slab", "minecraft:polished_granite_stairs",
            "minecraft:polished_tuff_slab", "minecraft:polished_tuff_stairs", "minecraft:polished_tuff_wall",
            "minecraft:powered_rail", "minecraft:prismarine_brick_slab", "minecraft:prismarine_brick_stairs",
            "minecraft:prismarine_slab", "minecraft:prismarine_stairs", "minecraft:prismarine_wall",
            "minecraft:purple_banner", "minecraft:purple_bed", "minecraft:purple_candle", "minecraft:purple_carpet",
            "minecraft:purple_stained_glass_pane", "minecraft:purpur_slab", "minecraft:purpur_stairs",
            "minecraft:quartz_slab", "minecraft:quartz_stairs", "minecraft:rail", "minecraft:red_banner",
            "minecraft:red_bed", "minecraft:red_candle", "minecraft:red_carpet",
            "minecraft:red_nether_brick_slab", "minecraft:red_nether_brick_stairs", "minecraft:red_nether_brick_wall",
            "minecraft:red_sandstone_slab", "minecraft:red_sandstone_stairs", "minecraft:red_sandstone_wall",
            "minecraft:red_stained_glass_pane", "minecraft:redstone_lamp", "minecraft:redstone_ore",
            "minecraft:redstone_torch", "minecraft:repeater", "minecraft:resin_brick_slab",
            "minecraft:resin_brick_stairs", "minecraft:resin_brick_wall", "minecraft:respawn_anchor",
            "minecraft:sandstone_slab", "minecraft:sandstone_stairs", "minecraft:sandstone_wall", "minecraft:scaffolding",
            "minecraft:sculk_catalyst", "minecraft:sculk_sensor", "minecraft:sculk_shrieker", "minecraft:sculk_vein",
            "minecraft:skeleton_skull", "minecraft:slime_block", "minecraft:small_amethyst_bud",
            "minecraft:smithing_table", "minecraft:smoker", "minecraft:smooth_quartz_slab",
            "minecraft:smooth_quartz_stairs", "minecraft:smooth_red_sandstone_slab",
            "minecraft:smooth_red_sandstone_stairs", "minecraft:smooth_sandstone_slab",
            "minecraft:smooth_sandstone_stairs", "minecraft:smooth_stone_slab", "minecraft:snow",
            "minecraft:soul_campfire", "minecraft:soul_lantern", "minecraft:soul_torch", "minecraft:spruce_button",
            "minecraft:spruce_door", "minecraft:spruce_fence", "minecraft:spruce_fence_gate",
            "minecraft:spruce_hanging_sign", "minecraft:spruce_pressure_plate", "minecraft:spruce_shelf",
            "minecraft:spruce_sign", "minecraft:spruce_trapdoor", "minecraft:sticky_piston",
            "minecraft:stone_brick_slab", "minecraft:stone_brick_stairs", "minecraft:stone_brick_wall",
            "minecraft:stone_button", "minecraft:stone_pressure_plate", "minecraft:stone_slab",
            "minecraft:stone_stairs", "minecraft:stonecutter", "minecraft:tnt", "minecraft:torch",
            "minecraft:tripwire_hook", "minecraft:tube_coral", "minecraft:tube_coral_fan", "minecraft:tuff_brick_slab",
            "minecraft:tuff_brick_stairs", "minecraft:tuff_brick_wall", "minecraft:tuff_slab", "minecraft:tuff_stairs",
            "minecraft:tuff_wall", "minecraft:vault", "minecraft:warped_button", "minecraft:warped_door",
            "minecraft:warped_fence", "minecraft:warped_fence_gate", "minecraft:warped_hanging_sign",
            "minecraft:warped_pressure_plate", "minecraft:warped_shelf", "minecraft:warped_sign",
            "minecraft:warped_slab", "minecraft:warped_stairs", "minecraft:warped_trapdoor",
            "minecraft:waxed_copper_bars", "minecraft:waxed_copper_bulb", "minecraft:waxed_copper_chain",
            "minecraft:waxed_copper_door", "minecraft:waxed_copper_golem_statue", "minecraft:waxed_copper_grate",
            "minecraft:waxed_copper_lantern", "minecraft:waxed_copper_trapdoor", "minecraft:waxed_cut_copper_slab",
            "minecraft:waxed_cut_copper_stairs", "minecraft:waxed_exposed_copper_bars",
            "minecraft:waxed_exposed_copper_bulb", "minecraft:waxed_exposed_copper_chain",
            "minecraft:waxed_exposed_copper_door", "minecraft:waxed_exposed_copper_golem_statue",
            "minecraft:waxed_exposed_copper_grate", "minecraft:waxed_exposed_copper_lantern",
            "minecraft:waxed_exposed_copper_trapdoor", "minecraft:waxed_exposed_cut_copper_slab",
            "minecraft:waxed_exposed_cut_copper_stairs", "minecraft:waxed_exposed_lightning_rod",
            "minecraft:waxed_lightning_rod", "minecraft:waxed_oxidized_copper_bars",
            "minecraft:waxed_oxidized_copper_bulb", "minecraft:waxed_oxidized_copper_chain",
            "minecraft:waxed_oxidized_copper_door", "minecraft:waxed_oxidized_copper_golem_statue",
            "minecraft:waxed_oxidized_copper_grate", "minecraft:waxed_oxidized_copper_lantern",
            "minecraft:waxed_oxidized_copper_trapdoor", "minecraft:waxed_oxidized_cut_copper_slab",
            "minecraft:waxed_oxidized_cut_copper_stairs", "minecraft:waxed_oxidized_lightning_rod",
            "minecraft:waxed_weathered_copper_bars", "minecraft:waxed_weathered_copper_bulb",
            "minecraft:waxed_weathered_copper_chain", "minecraft:waxed_weathered_copper_door",
            "minecraft:waxed_weathered_copper_golem_statue", "minecraft:waxed_weathered_copper_grate",
            "minecraft:waxed_weathered_copper_lantern", "minecraft:waxed_weathered_copper_trapdoor",
            "minecraft:waxed_weathered_cut_copper_slab", "minecraft:waxed_weathered_cut_copper_stairs",
            "minecraft:waxed_weathered_lightning_rod", "minecraft:weathered_copper_bars",
            "minecraft:weathered_copper_bulb", "minecraft:weathered_copper_chain", "minecraft:weathered_copper_door",
            "minecraft:weathered_copper_golem_statue", "minecraft:weathered_copper_grate",
            "minecraft:weathered_copper_lantern", "minecraft:weathered_copper_trapdoor",
            "minecraft:weathered_cut_copper_slab", "minecraft:weathered_cut_copper_stairs",
            "minecraft:weathered_lightning_rod", "minecraft:white_banner", "minecraft:white_bed",
            "minecraft:white_candle", "minecraft:white_carpet", "minecraft:white_stained_glass_pane",
            "minecraft:wither_skeleton_skull", "minecraft:yellow_banner", "minecraft:yellow_bed",
            "minecraft:yellow_candle", "minecraft:yellow_carpet", "minecraft:yellow_stained_glass_pane",
            "minecraft:zombie_head"
        ));
        PLANTS.setItemIds(Set.of(
            "minecraft:acacia_leaves", "minecraft:acacia_sapling", "minecraft:allium", "minecraft:azalea",
            "minecraft:azalea_leaves", "minecraft:azure_bluet", "minecraft:bamboo", "minecraft:beetroot_seeds",
            "minecraft:big_dripleaf", "minecraft:birch_leaves", "minecraft:birch_sapling", "minecraft:blue_orchid",
            "minecraft:brown_mushroom", "minecraft:bush", "minecraft:cactus", "minecraft:cactus_flower",
            "minecraft:cherry_leaves", "minecraft:cherry_sapling", "minecraft:chorus_flower", "minecraft:chorus_plant",
            "minecraft:closed_eyeblossom", "minecraft:cocoa_beans", "minecraft:cornflower", "minecraft:crimson_fungus",
            "minecraft:crimson_roots", "minecraft:dandelion", "minecraft:dark_oak_leaves", "minecraft:dark_oak_sapling",
            "minecraft:dead_bush", "minecraft:fern", "minecraft:firefly_bush", "minecraft:flowering_azalea",
            "minecraft:flowering_azalea_leaves", "minecraft:glow_berries", "minecraft:glow_lichen",
            "minecraft:golden_dandelion", "minecraft:hanging_roots", "minecraft:jungle_leaves",
            "minecraft:jungle_sapling", "minecraft:kelp", "minecraft:large_fern", "minecraft:leaf_litter",
            "minecraft:lilac", "minecraft:lily_of_the_valley", "minecraft:lily_pad", "minecraft:mangrove_leaves",
            "minecraft:mangrove_propagule", "minecraft:mangrove_roots", "minecraft:melon_seeds", "minecraft:moss_block",
            "minecraft:moss_carpet", "minecraft:muddy_mangrove_roots", "minecraft:nether_sprouts",
            "minecraft:nether_wart", "minecraft:oak_leaves", "minecraft:oak_sapling", "minecraft:open_eyeblossom",
            "minecraft:orange_tulip", "minecraft:oxeye_daisy", "minecraft:pale_hanging_moss",
            "minecraft:pale_moss_block", "minecraft:pale_moss_carpet", "minecraft:pale_oak_leaves",
            "minecraft:pale_oak_sapling", "minecraft:peony", "minecraft:pink_petals", "minecraft:pink_tulip",
            "minecraft:pitcher_plant", "minecraft:pitcher_pod", "minecraft:poppy", "minecraft:pumpkin_seeds",
            "minecraft:red_mushroom", "minecraft:red_tulip", "minecraft:rose_bush", "minecraft:sea_pickle",
            "minecraft:seagrass", "minecraft:short_dry_grass", "minecraft:short_grass", "minecraft:small_dripleaf",
            "minecraft:spore_blossom", "minecraft:spruce_leaves", "minecraft:spruce_sapling", "minecraft:sugar_cane",
            "minecraft:sunflower", "minecraft:sweet_berries", "minecraft:tall_dry_grass", "minecraft:tall_grass",
            "minecraft:torchflower", "minecraft:torchflower_seeds", "minecraft:twisting_vines", "minecraft:vine",
            "minecraft:warped_fungus", "minecraft:warped_roots", "minecraft:weeping_vines", "minecraft:wheat",
            "minecraft:wheat_seeds", "minecraft:white_tulip", "minecraft:wildflowers", "minecraft:wither_rose"
        ));
        FOOD.setItemIds(Set.of(
            "minecraft:apple", "minecraft:baked_potato", "minecraft:beef", "minecraft:beetroot",
            "minecraft:beetroot_soup", "minecraft:cake", "minecraft:carrot", "minecraft:chicken",
            "minecraft:chorus_fruit", "minecraft:cod", "minecraft:cooked_beef", "minecraft:cooked_chicken",
            "minecraft:cooked_cod", "minecraft:cooked_mutton", "minecraft:cooked_porkchop",
            "minecraft:cooked_rabbit", "minecraft:cooked_salmon", "minecraft:dried_kelp",
            "minecraft:enchanted_golden_apple", "minecraft:glow_berries", "minecraft:golden_apple",
            "minecraft:golden_carrot", "minecraft:melon_slice", "minecraft:mushroom_stew",
            "minecraft:mutton", "minecraft:poisonous_potato", "minecraft:porkchop", "minecraft:potato",
            "minecraft:pufferfish", "minecraft:pumpkin_pie", "minecraft:rabbit", "minecraft:rabbit_stew",
            "minecraft:rotten_flesh", "minecraft:salmon", "minecraft:spider_eye",
            "minecraft:suspicious_stew", "minecraft:sweet_berries", "minecraft:tropical_fish"
        ));
        MISC.setItemIds(Set.of(
            "minecraft:amethyst_shard", "minecraft:angler_pottery_sherd", "minecraft:archer_pottery_sherd",
            "minecraft:armadillo_scute", "minecraft:arms_up_pottery_sherd", "minecraft:black_dye",
            "minecraft:blade_pottery_sherd", "minecraft:blaze_powder", "minecraft:blaze_rod",
            "minecraft:blue_dye", "minecraft:blue_egg", "minecraft:bolt_armor_trim_smithing_template",
            "minecraft:bone", "minecraft:bone_meal", "minecraft:book", "minecraft:bowl",
            "minecraft:breeze_rod", "minecraft:brewer_pottery_sherd", "minecraft:brick",
            "minecraft:brown_dye", "minecraft:brown_egg", "minecraft:burn_pottery_sherd",
            "minecraft:charcoal", "minecraft:clay_ball", "minecraft:coast_armor_trim_smithing_template",
            "minecraft:copper_nugget", "minecraft:cyan_dye", "minecraft:danger_pottery_sherd",
            "minecraft:dragon_breath", "minecraft:dune_armor_trim_smithing_template",
            "minecraft:echo_shard", "minecraft:egg", "minecraft:enchanted_book",
            "minecraft:ender_eye", "minecraft:ender_pearl", "minecraft:experience_bottle",
            "minecraft:explorer_pottery_sherd", "minecraft:eye_armor_trim_smithing_template",
            "minecraft:feather", "minecraft:fermented_spider_eye", "minecraft:fire_charge",
            "minecraft:firework_rocket", "minecraft:firework_star", "minecraft:flint",
            "minecraft:flow_armor_trim_smithing_template", "minecraft:flow_pottery_sherd",
            "minecraft:friend_pottery_sherd", "minecraft:frogspawn", "minecraft:ghast_tear",
            "minecraft:glass_bottle", "minecraft:glistering_melon_slice", "minecraft:glow_ink_sac",
            "minecraft:glowstone_dust", "minecraft:gold_nugget", "minecraft:gray_dye",
            "minecraft:green_dye", "minecraft:gunpowder", "minecraft:guster_pottery_sherd",
            "minecraft:heart_of_the_sea", "minecraft:heart_pottery_sherd",
            "minecraft:heartbreak_pottery_sherd", "minecraft:heavy_core", "minecraft:honeycomb",
            "minecraft:host_armor_trim_smithing_template", "minecraft:howl_pottery_sherd",
            "minecraft:ink_sac", "minecraft:iron_nugget", "minecraft:leather",
            "minecraft:light_blue_dye", "minecraft:light_gray_dye", "minecraft:lime_dye",
            "minecraft:magenta_dye", "minecraft:magma_cream", "minecraft:miner_pottery_sherd",
            "minecraft:mourner_pottery_sherd", "minecraft:nautilus_shell", "minecraft:nether_brick",
            "minecraft:nether_star", "minecraft:netherite_upgrade_smithing_template",
            "minecraft:ominous_trial_key", "minecraft:orange_dye", "minecraft:paper",
            "minecraft:phantom_membrane", "minecraft:pink_dye", "minecraft:plenty_pottery_sherd",
            "minecraft:popped_chorus_fruit", "minecraft:prismarine_crystals",
            "minecraft:prismarine_shard", "minecraft:prize_pottery_sherd",
            "minecraft:purple_dye", "minecraft:quartz", "minecraft:rabbit_foot",
            "minecraft:rabbit_hide", "minecraft:raiser_armor_trim_smithing_template",
            "minecraft:red_dye", "minecraft:redstone", "minecraft:resin_brick",
            "minecraft:resin_clump", "minecraft:rib_armor_trim_smithing_template",
            "minecraft:scrape_pottery_sherd", "minecraft:sentry_armor_trim_smithing_template",
            "minecraft:shaper_armor_trim_smithing_template", "minecraft:sheaf_pottery_sherd",
            "minecraft:shelter_pottery_sherd", "minecraft:silence_armor_trim_smithing_template",
            "minecraft:skull_pottery_sherd", "minecraft:slime_ball", "minecraft:sniffer_egg",
            "minecraft:snort_pottery_sherd", "minecraft:snout_armor_trim_smithing_template",
            "minecraft:snowball", "minecraft:spire_armor_trim_smithing_template",
            "minecraft:stick", "minecraft:string", "minecraft:sugar",
            "minecraft:tide_armor_trim_smithing_template", "minecraft:trial_key",
            "minecraft:turtle_egg", "minecraft:turtle_scute",
            "minecraft:vex_armor_trim_smithing_template", "minecraft:ward_armor_trim_smithing_template",
            "minecraft:wayfinder_armor_trim_smithing_template", "minecraft:white_dye",
            "minecraft:wild_armor_trim_smithing_template", "minecraft:yellow_dye"
        ));
        TOOLS_AND_EQUIPMENT.setItemIds(Set.of(
            "minecraft:arrow", "minecraft:axolotl_bucket", "minecraft:birch_boat",
            "minecraft:black_bundle", "minecraft:blue_bundle", "minecraft:bow",
            "minecraft:brush", "minecraft:bucket", "minecraft:bundle",
            "minecraft:carrot_on_a_stick", "minecraft:chainmail_boots", "minecraft:chainmail_helmet",
            "minecraft:chainmail_leggings", "minecraft:clock", "minecraft:cod_bucket",
            "minecraft:compass", "minecraft:copper_axe", "minecraft:copper_boots",
            "minecraft:copper_helmet", "minecraft:copper_hoe", "minecraft:copper_horse_armor",
            "minecraft:copper_leggings", "minecraft:copper_nautilus_armor", "minecraft:copper_pickaxe",
            "minecraft:copper_shovel", "minecraft:copper_spear", "minecraft:copper_sword",
            "minecraft:crossbow", "minecraft:diamond_axe", "minecraft:diamond_boots",
            "minecraft:diamond_helmet", "minecraft:diamond_hoe", "minecraft:diamond_horse_armor",
            "minecraft:diamond_leggings", "minecraft:diamond_nautilus_armor", "minecraft:diamond_pickaxe",
            "minecraft:diamond_shovel", "minecraft:diamond_spear", "minecraft:diamond_sword",
            "minecraft:elytra", "minecraft:fishing_rod", "minecraft:flint_and_steel",
            "minecraft:golden_axe", "minecraft:golden_boots", "minecraft:golden_helmet",
            "minecraft:golden_hoe", "minecraft:golden_horse_armor", "minecraft:golden_nautilus_armor",
            "minecraft:golden_pickaxe", "minecraft:golden_shovel", "minecraft:golden_spear",
            "minecraft:golden_sword", "minecraft:gray_bundle",
            "minecraft:iron_axe", "minecraft:iron_helmet", "minecraft:iron_hoe",
            "minecraft:iron_horse_armor", "minecraft:iron_leggings", "minecraft:iron_nautilus_armor",
            "minecraft:iron_pickaxe", "minecraft:iron_shovel", "minecraft:iron_spear",
            "minecraft:iron_sword", "minecraft:lava_bucket", "minecraft:lead",
            "minecraft:leather_boots", "minecraft:leather_helmet", "minecraft:leather_horse_armor",
            "minecraft:leather_leggings", "minecraft:light_blue_bundle", "minecraft:light_gray_bundle",
            "minecraft:lime_bundle", "minecraft:mace", "minecraft:magenta_bundle",
            "minecraft:map", "minecraft:milk_bucket", "minecraft:minecart",
            "minecraft:name_tag", "minecraft:netherite_axe", "minecraft:netherite_boots",
            "minecraft:netherite_helmet", "minecraft:netherite_hoe", "minecraft:netherite_horse_armor",
            "minecraft:netherite_leggings", "minecraft:netherite_nautilus_armor",
            "minecraft:netherite_pickaxe", "minecraft:netherite_shovel", "minecraft:netherite_spear",
            "minecraft:netherite_sword", "minecraft:oak_boat", "minecraft:powder_snow_bucket",
            "minecraft:pufferfish_bucket", "minecraft:recovery_compass", "minecraft:saddle",
            "minecraft:salmon_bucket", "minecraft:shears", "minecraft:shield",
            "minecraft:spectral_arrow", "minecraft:spyglass", "minecraft:stone_axe",
            "minecraft:stone_hoe", "minecraft:stone_pickaxe", "minecraft:stone_shovel",
            "minecraft:stone_spear", "minecraft:stone_sword", "minecraft:tadpole_bucket",
            "minecraft:tipped_arrow", "minecraft:tnt_minecart", "minecraft:totem_of_undying",
            "minecraft:trident", "minecraft:tropical_fish_bucket", "minecraft:turtle_helmet",
            "minecraft:water_bucket", "minecraft:white_bundle", "minecraft:wolf_armor",
            "minecraft:wooden_axe", "minecraft:wooden_hoe", "minecraft:wooden_pickaxe",
            "minecraft:wooden_shovel", "minecraft:wooden_spear", "minecraft:wooden_sword",
            "minecraft:writable_book"
        ));
        MINERALS.setItemIds(Set.of(
            "minecraft:ancient_debris", "minecraft:coal", "minecraft:copper_ingot",
            "minecraft:diamond", "minecraft:diamond_block", "minecraft:emerald",
            "minecraft:emerald_block", "minecraft:gold_block", "minecraft:gold_ingot",
            "minecraft:iron_ingot", "minecraft:lapis_block", "minecraft:lapis_lazuli",
            "minecraft:netherite_block", "minecraft:netherite_ingot", "minecraft:netherite_scrap",
            "minecraft:raw_copper", "minecraft:raw_gold", "minecraft:raw_iron",
            "minecraft:redstone_block"
        ));
    }
}
